"""
Session report generator for the classroom cognitive-load monitor.

Reads the CSV produced by ExtendedMoodClassroomMonitor.save_logs()
(columns: Name, Attentiveness, AttConf, Mood, MoodConf, CognitiveLoad,
PERCLOS, Timestamp) and produces a multi-page PDF report:

  - One page per student: cognitive-load trend over the session,
    attentiveness breakdown, mood breakdown, and a plain-language
    "concern flag" summary.
  - One class-overview page: everyone's average load ranked side by
    side, with flagged students called out.

FLAGGING (why a student gets highlighted for follow-up):
  - Sustained high cognitive load (not just one bad moment -- looks
    for several high-load samples in a row, since one rough minute
    doesn't mean much but a sustained pattern does)
  - High share of negative mood samples (sad/angry/fearful/furrowed)
  - High share of disengaged attentiveness samples (sleepy/looking_away)

This produces FLAGS FOR A HUMAN TO FOLLOW UP ON, not a diagnosis.
The output intentionally uses language like "worth checking in on"
rather than naming a condition (stress/depression/anxiety) -- a
counselor or staff member should be the one to have that
conversation, not a label generated by face analysis. See the
scope note in mood_detection_v4.py for the same reasoning.

Usage:
    python session_report.py session_logs.csv
    # or import and call generate_report() from main_dashboard.py
"""
"""
Session report generator - unchanged from the original. It already only
reads the CSV log file and produces a PDF/PNG report, so nothing about it
depended on a local camera or display; it works as-is on a server.
"""

import os
import sys
import statistics
from datetime import datetime
from collections import defaultdict

import pandas as pd
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import matplotlib.dates as mdates
from matplotlib.backends.backend_pdf import PdfPages

ATT_COLORS = {
    "attentive": "#22c55e", "focused": "#4ade80", "distracted": "#fb923c",
    "looking_away": "#ef4444", "sleepy": "#94a3b8", "yawning": "#a78bfa",
}
MOOD_COLORS = {
    "happy": "#facc15", "sad": "#60a5fa", "angry": "#dc2626",
    "furrowed": "#f97316", "confused": "#f59e0b", "surprised": "#ec4899",
    "fearful": "#7c3aed", "neutral": "#9ca3af",
}
NEGATIVE_MOODS = {"sad", "angry", "furrowed", "fearful"}
DISENGAGED_STATES = {"sleepy", "looking_away", "yawning"}

HIGH_LOAD_THRESHOLD = 55.0
SUSTAINED_STREAK_MIN = 4
NEGATIVE_MOOD_SHARE_FLAG = 0.35
DISENGAGED_SHARE_FLAG = 0.45
MIN_SAMPLES_FOR_PAGE = 5


def _longest_streak_above(values, threshold):
    best = cur = 0
    for v in values:
        if v >= threshold:
            cur += 1
            best = max(best, cur)
        else:
            cur = 0
    return best


def _evaluate_flags(student_df):
    loads = student_df["CognitiveLoad"].tolist()
    moods = student_df["Mood"].tolist()
    attentiveness = student_df["Attentiveness"].tolist()
    n = len(student_df)
    reasons = []
    avg_load = statistics.mean(loads) if loads else 0.0
    streak = _longest_streak_above(loads, HIGH_LOAD_THRESHOLD)
    if streak >= SUSTAINED_STREAK_MIN:
        reasons.append(f"sustained high cognitive load ({streak} samples in a row >= {HIGH_LOAD_THRESHOLD:.0f})")
    neg_share = sum(1 for m in moods if m in NEGATIVE_MOODS) / n if n else 0.0
    if neg_share >= NEGATIVE_MOOD_SHARE_FLAG:
        reasons.append(f"negative mood in {neg_share*100:.0f}% of samples")
    dis_share = sum(1 for a in attentiveness if a in DISENGAGED_STATES) / n if n else 0.0
    if dis_share >= DISENGAGED_SHARE_FLAG:
        reasons.append(f"disengaged in {dis_share*100:.0f}% of samples")
    return {"avg_load": avg_load, "flagged": len(reasons) > 0, "reasons": reasons,
            "neg_share": neg_share, "dis_share": dis_share}


def _student_page(fig, student_df, name, flag_info):
    gs = fig.add_gridspec(2, 2, height_ratios=[1.1, 1], hspace=0.45, wspace=0.35)
    ax_load = fig.add_subplot(gs[0, :])
    times = pd.to_datetime(student_df["Timestamp"])
    loads = student_df["CognitiveLoad"]
    ax_load.plot(times, loads, color="#2563eb", linewidth=1.8, marker="o", markersize=3)
    ax_load.axhline(HIGH_LOAD_THRESHOLD, color="#ef4444", linestyle="--", linewidth=1,
                     label=f"High-load threshold ({HIGH_LOAD_THRESHOLD:.0f})")
    ax_load.fill_between(times, loads, HIGH_LOAD_THRESHOLD,
                          where=(loads >= HIGH_LOAD_THRESHOLD), color="#ef4444", alpha=0.15)
    ax_load.set_ylim(0, 100)
    ax_load.set_title(f"{name} - Cognitive Load Over Session", fontsize=12, fontweight="bold")
    ax_load.set_ylabel("Cognitive Load (0-100)")
    ax_load.legend(loc="upper right", fontsize=8)
    ax_load.xaxis.set_major_formatter(mdates.DateFormatter("%H:%M:%S"))
    fig.autofmt_xdate(rotation=30)

    ax_att = fig.add_subplot(gs[1, 0])
    att_counts = student_df["Attentiveness"].value_counts()
    colors = [ATT_COLORS.get(c, "#999999") for c in att_counts.index]
    ax_att.pie(att_counts.values, labels=att_counts.index, colors=colors, autopct="%1.0f%%", textprops={"fontsize": 8})
    ax_att.set_title("Attentiveness", fontsize=10)

    ax_mood = fig.add_subplot(gs[1, 1])
    mood_counts = student_df["Mood"].value_counts()
    colors = [MOOD_COLORS.get(c, "#999999") for c in mood_counts.index]
    ax_mood.pie(mood_counts.values, labels=mood_counts.index, colors=colors, autopct="%1.0f%%", textprops={"fontsize": 8})
    ax_mood.set_title("Mood", fontsize=10)

    if flag_info["flagged"]:
        banner = "FLAGGED FOR FOLLOW-UP: " + "; ".join(flag_info["reasons"])
        fig.text(0.5, 0.965, banner, ha="center", va="top", fontsize=9.5, color="white", fontweight="bold",
                  bbox=dict(boxstyle="round,pad=0.4", facecolor="#dc2626", edgecolor="none"))
    else:
        fig.text(0.5, 0.965, "No sustained concern patterns this session", ha="center", va="top",
                  fontsize=9.5, color="white", bbox=dict(boxstyle="round,pad=0.4", facecolor="#16a34a", edgecolor="none"))


def _class_overview_page(fig, df, per_student_flags):
    ax = fig.add_subplot(111)
    names = list(per_student_flags.keys())
    avg_loads = [per_student_flags[n]["avg_load"] for n in names]
    order = sorted(range(len(names)), key=lambda i: avg_loads[i], reverse=True)
    names = [names[i] for i in order]
    avg_loads = [avg_loads[i] for i in order]
    colors = ["#dc2626" if per_student_flags[n]["flagged"] else "#2563eb" for n in names]
    bars = ax.barh(names, avg_loads, color=colors)
    ax.axvline(HIGH_LOAD_THRESHOLD, color="#ef4444", linestyle="--", linewidth=1,
               label=f"High-load threshold ({HIGH_LOAD_THRESHOLD:.0f})")
    ax.set_xlim(0, 100)
    ax.set_xlabel("Average Cognitive Load (0-100)")
    ax.set_title("Class Overview - Average Cognitive Load per Student\n(red = flagged for follow-up)",
                  fontsize=12, fontweight="bold")
    ax.legend(loc="lower right", fontsize=8)
    for bar, val in zip(bars, avg_loads):
        ax.text(val + 1.5, bar.get_y() + bar.get_height() / 2, f"{val:.1f}", va="center", fontsize=8)


def generate_report(log_file="cognitive_load_log.csv", output_dir="session_reports"):
    if not os.path.isfile(log_file):
        return None
    try:
        df = pd.read_csv(log_file)
    except Exception:
        return None
    if df.empty:
        return None

    os.makedirs(output_dir, exist_ok=True)
    timestamp = datetime.now().strftime("%Y%m%dT%H%M%SZ")
    pdf_path = os.path.join(output_dir, f"session_report-{timestamp}.pdf")
    flags_csv_path = os.path.join(output_dir, f"flagged_students-{timestamp}.csv")
    png_dir = os.path.join(output_dir, f"session_report-{timestamp}_png")
    os.makedirs(png_dir, exist_ok=True)

    per_student_flags = {}
    with PdfPages(pdf_path) as pdf:
        for name, student_df in df.groupby("Name"):
            student_df = student_df.sort_values("Timestamp")
            if len(student_df) < MIN_SAMPLES_FOR_PAGE:
                per_student_flags[name] = {
                    "avg_load": statistics.mean(student_df["CognitiveLoad"]) if len(student_df) else 0.0,
                    "flagged": False, "reasons": [], "neg_share": 0.0, "dis_share": 0.0,
                }
                continue
            try:
                flag_info = _evaluate_flags(student_df)
                per_student_flags[name] = flag_info
                fig = plt.figure(figsize=(11, 8.5))
                _student_page(fig, student_df, name, flag_info)
                pdf.savefig(fig)
                safe_name = "".join(c if c.isalnum() or c in "-_" else "_" for c in str(name))
                fig.savefig(os.path.join(png_dir, f"{safe_name}.png"), dpi=150, bbox_inches="tight")
                plt.close(fig)
            except Exception:
                continue

        try:
            fig = plt.figure(figsize=(11, 8.5))
            _class_overview_page(fig, df, per_student_flags)
            pdf.savefig(fig)
            fig.savefig(os.path.join(png_dir, "_class_overview.png"), dpi=150, bbox_inches="tight")
            plt.close(fig)
        except Exception:
            pass

    flagged_rows = [
        {"Name": n, "AvgLoad": round(f["avg_load"], 1), "Reasons": "; ".join(f["reasons"])}
        for n, f in per_student_flags.items() if f["flagged"]
    ]
    pd.DataFrame(flagged_rows).to_csv(flags_csv_path, index=False)
    return pdf_path, flags_csv_path, png_dir


if __name__ == "__main__":
    log_arg = sys.argv[1] if len(sys.argv) > 1 else "cognitive_load_log.csv"
    generate_report(log_arg)